# Generated by Django 3.1.5 on 2021-01-09 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ('name',), 'verbose_name': 'districts', 'verbose_name_plural': 'distritos'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='cities'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=100, verbose_name='districts'),
        ),
        migrations.AlterField(
            model_name='person',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chainapp.district', verbose_name='districts'),
        ),
    ]
