# Generated by Django 3.1.5 on 2021-01-09 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chainapp', '0003_auto_20210109_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='categories')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chainapp.district', verbose_name='Districts')),
            ],
            options={
                'verbose_name': 'categories',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
    ]
