# Generated by Django 3.1.5 on 2021-01-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainapp', '0004_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='district',
        ),
        migrations.AddField(
            model_name='category',
            name='district',
            field=models.ManyToManyField(to='chainapp.District', verbose_name='Districts'),
        ),
    ]
