# Generated by Django 3.1.5 on 2021-01-09 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chainapp', '0005_auto_20210110_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='district',
        ),
        migrations.AddField(
            model_name='person',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chainapp.category', verbose_name='categories'),
        ),
    ]
