# Generated by Django 3.1.5 on 2021-01-10 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chainapp', '0006_auto_20210110_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='category',
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='subcategories')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chainapp.category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Subcategories',
                'verbose_name_plural': 'Subcategories',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='person',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chainapp.subcategory', verbose_name='Subcategories'),
        ),
    ]
