# Generated by Django 3.1.5 on 2021-01-10 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chainapp', '0008_person_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='gender',
        ),
    ]
