# Generated by Django 3.1.5 on 2021-01-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainapp', '0009_remove_person_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='district',
        ),
        migrations.RemoveField(
            model_name='person',
            name='district',
        ),
        migrations.AddField(
            model_name='person',
            name='district',
            field=models.ManyToManyField(to='chainapp.District', verbose_name='Districts'),
        ),
    ]
