# Generated by Django 3.1.5 on 2021-01-10 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chainapp', '0012_auto_20210110_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='district',
        ),
        migrations.AddField(
            model_name='person',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chainapp.district', verbose_name='Districts'),
        ),
    ]
