# Generated by Django 3.1.5 on 2021-01-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainapp', '0013_auto_20210110_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='district',
            field=models.ManyToManyField(to='chainapp.District', verbose_name='Districts'),
        ),
    ]
