# Generated by Django 3.1.5 on 2021-01-10 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chainapp', '0014_subcategory_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='district',
        ),
        migrations.AddField(
            model_name='category',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chainapp.district', verbose_name='Districts'),
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='district',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chainapp.district', verbose_name='Districts'),
        ),
    ]
