# Generated by Django 3.1.5 on 2021-02-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainapp', '0015_auto_20210110_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
