# Generated by Django 3.1.5 on 2021-02-28 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chainapp', '0017_remove_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static/products', verbose_name='image'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chainapp.person')),
            ],
        ),
    ]
