# Generated by Django 3.1.5 on 2021-02-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainapp', '0018_auto_20210228_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='static/products'),
        ),
    ]
