# Generated by Django 3.1.5 on 2021-03-02 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chainapp', '0020_auto_20210301_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='car_type')),
            ],
            options={
                'verbose_name': 'car_type',
                'verbose_name_plural': 'car_types',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Makes')),
            ],
            options={
                'verbose_name': 'Make',
                'verbose_name_plural': 'Makes',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Model_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='model_types')),
                ('make', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chainapp.make', verbose_name='Model_types')),
            ],
            options={
                'verbose_name': 'model_type',
                'verbose_name_plural': 'model_types',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='code')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, max_length=150, null=True)),
                ('marked_price', models.PositiveIntegerField(blank=True, max_length=10, null=True)),
                ('selling_price', models.PositiveIntegerField(blank=True, max_length=10, null=True)),
                ('return_policy', models.CharField(blank=True, max_length=300, null=True)),
                ('available', models.BooleanField(default=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='static/products', verbose_name='image')),
                ('images1', models.ImageField(blank=True, null=True, upload_to='static/products', verbose_name='image1')),
                ('images2', models.ImageField(blank=True, null=True, upload_to='static/products', verbose_name='image2')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('car_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chainapp.car_type', verbose_name='Car_types')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='district',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='district',
        ),
        migrations.RemoveField(
            model_name='person',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='category',
            name='district',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='district',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chainapp.subcategory', verbose_name='Subcategories'),
        ),
        migrations.AddField(
            model_name='car_type',
            name='model_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chainapp.model_type', verbose_name='Model_types'),
        ),
        migrations.AddField(
            model_name='category',
            name='car_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chainapp.car_type', verbose_name='Car_types'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='car_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chainapp.car_type', verbose_name='Car_types'),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'slug')},
        ),
    ]
