# Generated by Django 3.1.5 on 2021-03-07 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chainapp', '0023_auto_20210306_1800'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
