# Generated by Django 3.1.5 on 2021-03-14 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chainapp', '0024_delete_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='selling_price',
            new_name='price',
        ),
    ]
