# Generated by Django 3.1.5 on 2021-03-14 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chainapp', '0025_auto_20210314_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
    ]
