# Generated by Django 3.1.5 on 2021-03-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainapp', '0027_auto_20210314_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
