# Generated by Django 3.1.5 on 2021-03-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainapp', '0028_cartproduct_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.FloatField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='subtotal',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
