# Generated by Django 3.1.5 on 2021-03-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainapp', '0029_auto_20210315_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='rate',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
