# Generated by Django 3.1.5 on 2021-03-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainapp', '0032_auto_20210316_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_type',
            name='name',
            field=models.CharField(max_length=300, verbose_name='car_type'),
        ),
    ]
