# Generated by Django 3.1.5 on 2021-04-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainapp', '0035_auto_20210329_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='image',
        ),
        migrations.RemoveField(
            model_name='alternative',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='altproduct',
            field=models.ManyToManyField(to='chainapp.Alternative'),
        ),
    ]
