# Generated by Django 3.1.5 on 2021-04-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainapp', '0036_auto_20210404_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='altproduct',
        ),
        migrations.AddField(
            model_name='product',
            name='altproduct',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='codes'),
        ),
        migrations.DeleteModel(
            name='Alternative',
        ),
    ]
