# Generated by Django 3.1.5 on 2021-04-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainapp', '0037_auto_20210404_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='altproduct',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='codes'),
        ),
    ]
