# Generated by Django 3.1.5 on 2021-04-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chainapp', '0038_auto_20210404_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='altproduct',
            field=models.TextField(blank=True, null=True, verbose_name='codes'),
        ),
    ]
